### ISSUE TITLE
Text input impssible to read

### ISSUE THREAD

**Issue by szilviu** [akshay2000/XBMCRemoteWP#1]
Lumia 520 - Romania orange
Black text on black bacground when setting up xbmc serer
![wp_ss_20140510_0001 1](https://cloud.githubusercontent.com/assets/7541718/2935868/1877d6d6-d832-11e3-93e3-5e42d92bd471.png)

Black text on black bacground when opening ip adress + region separators. RO uses "," instead of "." . Maybe force input by using standard keyborad, not only numbers 
![wp_ss_20140510_0002 1](https://cloud.githubusercontent.com/assets/7541718/2935875/77a86ba2-d832-11e3-9dc0-60b9749c8937.png)

**Comment by akshay2000** [comment]
The text input issue only bugs people with 'Light' theme. Use dark theme as a workaround.  
You can type IP address in Name field and copy it to the IP field.  
Both the issues are fixed in latest commits. Next version would contain them. Please check out and report back.

**Comment by akshay2000** [comment]
Fixed in the latest update,
