### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by SaintDekar** [akshay2000/XBMCRemoteWP#3]
So far I have been unable to connect this app to any XBMC clients, windows and android.  I fill out the required infor but consistantly get this error. 
![qijgyjj](https://cloud.githubusercontent.com/assets/7545145/2937376/47154242-d89d-11e3-9006-cd6453f03be8.png)

Reinstalling app does not resolve issue and the connection works with other remote apps currently.

**Comment by akshay2000** [comment]
Already fixed in this commit: https://github.com/akshay2000/XBMCRemoteWP/commit/a6a9d7c39f4ad1b8bae2d5c8e858d392de1d6d6b. Next update in store will solve this.
