### ISSUE TITLE
Can not delete or edit connections

### ISSUE THREAD

**Issue by SaintDekar** [akshay2000/XBMCRemoteWP#4]
Although currently I can't even connect to a device, you also can not edit nor delete connections. Obviously a needed function, just wanted to note it here.

**Comment by akshay2000** [comment]
Thanks for the reminder. There's already delete functionality made available in this merge: https://github.com/akshay2000/XBMCRemoteWP/commit/bfa0b0257355563cc457ed9b25994ae1b5e9dd66
Should 'edit' be explicitly added or deleting the old one and adding a new one would suffice?

**Comment by SaintDekar** [comment]
I feel like edit is an important function design wise. Delete and re write is fine, but convenience is important in a remote app.

**Comment by akshay2000** [comment]
Alright! I have added the edit functionality. Hope that suits you. Tomorrow's update will bring that feature.

**Comment by BrianLima** [comment]
I can't even connect too, does the "Name" just stands for local name, or it is the server name, I've checked every option, from allowing the XBMC to be controlled, the port, the ip, with and without password, and nothing, I couldn't figure if it is my server, or the ping method, while i'm debugging it simple don return nothing, but my server is up and running and other XBMC apps on my PC work very well.

**Comment by akshay2000** [comment]
@BrianLima First make sure that the device can access the XBMC server at all. Go to the Internet Explorer on phone and enter full address of the server (for example, http://10.0.0.9:8080). You should be able to get the XBMC web UI.  
And yeah, the Name is purely local. It has got nothing to do with server.
